# Etapa de construcción
FROM node:18.16.0-alpine as build-stage

RUN npm install -g typescript

# RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY bookExchangeFrontEnd2/package*.json ./

COPY . .

RUN ls -al

RUN npm install

RUN npm run build

# Etapa de producción
FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
