version: "3"

services:
  frontend:
    container_name: frontEndBookExchange
    build:
      context: ./bookExchangeFrontEnd2
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    networks:
      - my-network
    depends_on:
      - web
  web:
    container_name: bookExchangeBackEndB
    restart: always
    build:
      context: ./nodeBackenBookEnxachange
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3500"
    networks:
      - my-network
    links:
      - mongo
  mongo:
    container_name: mongoBookExchangeBBDD
    image: mongo
    networks:
      - my-network
    ports:
      - "27050:27017"
networks:
  my-network:
    driver: bridge
    name: my-network